# Generated by Django 5.2.13 on 2026-04-21 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_unused_business_fields_and_cleanup_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
    ]
